version: "3.9"

######################
#### -- Network -- ####
#######################
networks:
  hecams_bridge_network:
    name: hecams_network_x
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.1/24"
          gateway: 172.21.0.1


######################
#### -- Development -- ####
#######################

services:
  hecams-ui-service:
    image: hecams-ui:1.0
    container_name: hecams-ui-service
    build:
      context: .
      target: development
    ports:
      - "8080:3000"
    volumes:
      - ./src:/app/src
    restart:
      always
    networks:
      hecams_bridge_network:
        ipv4_address: 172.21.0.81
