// access token
export const ACCESS_TOKEN_LOADING = "ACCESS_TOKEN_LOADING" 
export const ACCESS_TOKEN_FAILED = "ACCESS_TOKEN_FAILED" 
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS"

// auth
export const AUTHENTICATION_LOADING = "AUTHENTICATION_LOADING" 
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED" 
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS" 